### PR TITLE
Enable impl_trait_in_assoc_type feature

### PR DESCRIPTION
**Pull request by jnalanko**
The build is currently broken on latest nightly because the feature impl_trait_in_assoc_type has been put behind a feature gate. I am getting errors like:

```
error[E0658]: `impl Trait` in associated types is unstable
  --> crates/hashes/src/cn_nthash.rs:63:25
   |
63 |       type IteratorType = impl Iterator<
   |  _________________________^
64 | |         Item = <CanonicalNtHashIteratorFactory as HashFunctionFactory>...
65 | |     >;
   | |_____^
   |
   = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information
   = help: add `#![feature(impl_trait_in_assoc_type)]` to the crate attributes to enable
```

This commit fixes these errors.

### CODE REVIEW

**Review by rchikhi — APPROVED** [review]
Yep, had the same issue and implemented the same fix. It compiles fine with v1.70.0-nightly, the problem occurs with >= v1.71.0-nighly
